services:
  postgres:
    image: postgres
    container_name: rest-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: restapi
    ports:
      - "5432:5432"
    volumes:
      - rest-db-data:/var/lib/postgresql/data

volumes:
  rest-db-data: